# Generated by Django 5.1.3 on 2024-11-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialTrackerApp', '0004_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='project',
        ),
    ]
