# Generated by Django 5.1.3 on 2024-11-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialTrackerApp', '0005_remove_location_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
