# Generated by Django 5.1.3 on 2024-11-15 18:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialTrackerApp', '0008_item_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.FloatField()),
                ('main_img', models.ImageField(blank=True, default="{% static 'img/MaterialTrackerApp/generic_user.png' %}", upload_to='')),
                ('quality_exp_date', models.DateTimeField()),
                ('cost', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialTrackerApp.currency')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialTrackerApp.location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialTrackerApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default="{% static 'img/MaterialTrackerApp/generic_user.png' %}", upload_to='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialTrackerApp.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_exp_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialTrackerApp.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialTrackerApp.location')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialTrackerApp.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_location', to='MaterialTrackerApp.location')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialTrackerApp.material')),
                ('origin_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_location', to='MaterialTrackerApp.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transactions', to='MaterialTrackerApp.project')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialTrackerApp.material')),
                ('origin_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_transactions', to='MaterialTrackerApp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='item',
        ),
        migrations.DeleteModel(
            name='transaction',
        ),
    ]
