# Generated by Django 5.1.3 on 2024-11-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialTrackerApp', '0011_mtmaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTCars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='NAME')),
                ('mpg', models.FloatField(db_column='MPG')),
                ('cyl', models.IntegerField(db_column='CYL')),
                ('disp', models.FloatField(db_column='DISP')),
                ('hp', models.IntegerField(db_column='HP')),
                ('wt', models.FloatField(db_column='WT')),
                ('qsec', models.FloatField(db_column='QSEC')),
                ('vs', models.IntegerField(db_column='VS')),
                ('am', models.IntegerField(db_column='AM')),
                ('gear', models.IntegerField(db_column='GEAR')),
            ],
        ),
        migrations.DeleteModel(
            name='MTMaterials',
        ),
    ]
