# Generated by Django 5.1.3 on 2024-12-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialTrackerApp', '0012_mtcars_delete_mtmaterials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='currency',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='MTCars',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
