# Generated by Django 5.1.3 on 2024-12-03 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialTrackerApp', '0013_alter_material_currency_delete_mtcars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('dolar_value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='materiallocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='materiallocation',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialmovements',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='materialmovements',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialmovements',
            name='origin_location',
        ),
        migrations.RemoveField(
            model_name='materialmovements',
            name='user',
        ),
        migrations.RemoveField(
            model_name='materialtransaction',
            name='destination_project',
        ),
        migrations.RemoveField(
            model_name='materialtransaction',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialtransaction',
            name='origin_project',
        ),
        migrations.RemoveField(
            model_name='materialtransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='material',
            name='quality_exp_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.DeleteModel(
            name='MaterialInspection',
        ),
        migrations.DeleteModel(
            name='MaterialLocation',
        ),
        migrations.DeleteModel(
            name='MaterialMovements',
        ),
        migrations.DeleteModel(
            name='MaterialTransaction',
        ),
        migrations.DeleteModel(
            name='ProjectUser',
        ),
    ]
