# Generated by Django 5.1.3 on 2024-12-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialTrackerApp', '0014_currency_remove_materiallocation_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='capacity',
        ),
    ]
