# Generated by Django 5.1.3 on 2024-12-03 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialTrackerApp', '0015_remove_material_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='exp_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
