# Generated by Django 5.1.3 on 2024-12-03 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialTrackerApp', '0016_material_exp_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='exp_date',
            new_name='quality_exp_date',
        ),
    ]
